[options]
girs_dir = "gir-files"
library = "Gio"
version = "2.0"
min_cfg_version = "2.32"
target_path = "."
work_mode = "normal"

generate = [
    "Gio.Action",
    "Gio.ActionMap",
    "Gio.AppInfo",
    "Gio.AppInfoCreateFlags",
    "Gio.AppInfoMonitor",
    "Gio.AppLaunchContext",
    "Gio.ApplicationFlags",
    "Gio.ApplicationCommandLine",
    "Gio.AskPasswordFlags",
    "Gio.AsyncResult",
    "Gio.BufferedOutputStream",
    "Gio.Cancellable",
    "Gio.CharsetConverter",
    "Gio.ConverterFlags",
    "Gio.ConverterResult",
    "Gio.ConverterInputStream",
    "Gio.ConverterOutputStream",
    "Gio.Credentials",
    "Gio.DataOutputStream",
    "Gio.DataStreamByteOrder",
    "Gio.DataStreamNewlineType",
    "Gio.DBusActionGroup",
    #"Gio.DBusAnnotationInfo",
    #"Gio.DBusArgInfo",
    "Gio.DBusAuthObserver",
    "Gio.DBusMessageByteOrder",
    "Gio.DBusCallFlags",
    "Gio.DBusCapabilityFlags",
    "Gio.DBusConnectionFlags",
    "Gio.DBusInterfaceInfo",
    "Gio.DBusMessageFlags",
    "Gio.DBusMessageHeaderField",
    "Gio.DBusMessageType",
    "Gio.DBusSendMessageFlags",
    "Gio.DBusServer",
    "Gio.DBusServerFlags",
    "Gio.DesktopAppInfoLookup",
    "Gio.Drive",
    "Gio.FileCreateFlags",
    "Gio.FileInfo",
    "Gio.FileQueryInfoFlags",
    "Gio.FileType",
    "Gio.Icon",
    "Gio.Initable",
    #"Gio.InputMessage",
    "Gio.IOStreamSpliceFlags",
    #"Gio.LoadableIcon",
    "Gio.Menu",
    "Gio.MenuAttributeIter",
    "Gio.MenuItem",
    "Gio.MenuLinkIter",
    "Gio.MenuModel",
    "Gio.MountOperation",
    "Gio.MountOperationResult",
    "Gio.NotificationPriority",
    #"Gio.OutputMessage",
    "Gio.OutputStreamSpliceFlags",
    "Gio.PasswordSave",
    "Gio.Permission",
    "Gio.PollableInputStream",
    "Gio.PollableOutputStream",
    "Gio.RemoteActionGroup",
    "Gio.ResourceError",
    "Gio.ResourceLookupFlags",
    "Gio.Seekable",
    "Gio.SettingsBindFlags",
    "Gio.SettingsSchema",
    "Gio.SimpleActionGroup",
    "Gio.SimplePermission",
    "Gio.ThemedIcon",
    "Gio.TlsCertificate",
    "Gio.TlsCertificateFlags",
    "Gio.Volume",
]

ignore = [
]

manual = [
    "Gio.FileInputStream",
    "Gio.FileIOStream",
    "Gio.FileOutputStream",
    "GLib.Bytes",
    "GLib.Error",
    "GLib.Variant",
    "GLib.VariantType",
    "GObject.Object",
]

[[object]]
name = "Gio.*"
status = "generate"
    [[object.function]]
    pattern = "unix_.+"
    cfg_condition = "unix"
    [[object.function]]
    pattern = "pollable_stream_.+"
    #belong to Stream, works only with PollableStream, need mutable buffer reference
    ignore = true

[[object]]
name = "Gio.ActionGroup"
status = "generate"
    [[object.function]]
    name = "query_action"
    ignore = true

[[object]]
name = "Gio.Application"
status = "generate"
    [[object.signal]]
    name = "open"
    ignore = true
    [[object.function]]
    name = "run"
    ignore = true

[[object]]
name = "Gio.BufferedInputStream"
status = "generate"
    [[object.function]]
    name = "fill_async"
    #manual return type
    ignore = true
    [[object.function]]
    name = "peek"
    #have almost same peek_buffer
    ignore = true

[[object]]
name = "Gio.DataInputStream"
status = "generate"
    [[object.function]]
    name = "read_line"
    #return vec of u8
    ignore = true

[[object]]
name = "Gio.DBusConnection"
status = "generate"
    [[object.function]]
    name = "send_message"
    # uses glib.Volatile type
    ignore = true
    [[object.function]]
    name = "send_message_with_reply_sync"
    # uses glib.Volatile type
    ignore = true

[[object]]
name = "Gio.DBusMessage"
status = "generate"
    [[object.function]]
    name = "get_header_fields"
    ignore = true

[[object]]
name = "Gio.DesktopAppInfo"
status = "generate"
    [[object.function]]
    name = "search"
    ignore = true

[[object]]
name = "Gio.File"
status = "generate"
    [[object.function]]
    name = "new_for_path"
        [object.function.return]
        nullable = false
    [[object.function]]
    name = "new_for_uri"
        [object.function.return]
        nullable = false
    [[object.function]]
    name = "new_for_commandline_arg"
        [object.function.return]
        nullable = false
    [[object.function]]
    name = "new_for_commandline_arg_and_cwd"
        [object.function.return]
        nullable = false
    [[object.function]]
    name = "hash"
    ignore = true
    [[object.function]]
    name = "enumerate_children_async"
    # FileEnumerator
    ignore = true
    [[object.function]]
    name = "find_enclosing_mount_async"
    # Mount
    ignore = true
    [[object.function]]
    name = "append_to_async"
    # wrong async return
    ignore = true
    [[object.function]]
    name = "create_async"
    # wrong async return
    ignore = true
    [[object.function]]
    name = "create_readwrite_async"
    # wrong async return
    ignore = true
    [[object.function]]
    name = "open_readwrite_async"
    # wrong async return
    ignore = true
    [[object.function]]
    name = "query_filesystem_info_async"
    # wrong async return
    ignore = true
    [[object.function]]
    name = "query_info_async"
    # wrong async return
    ignore = true
    [[object.function]]
    name = "read_async"
    # wrong async return
    ignore = true
    [[object.function]]
    name = "replace_async"
    # wrong async return
    ignore = true
    [[object.function]]
    name = "replace_readwrite_async"
    # wrong async return
    ignore = true
    [[object.function]]
    name = "set_display_name_async"
    # wrong async return
    ignore = true

[[object]]
name = "Gio.FilterInputStream"
status = "generate"
    [[object.property]]
    name = "base-stream"
    #readonly
    ignore = true

[[object]]
name = "Gio.FilterOutputStream"
status = "generate"
    [[object.property]]
    name = "base-stream"
    #readonly
    ignore = true

[[object]]
name = "Gio.IOStream"
status = "generate"
    [[object.function]]
    name = "splice_async"
    #g_io_stream_splice_finish accept only 2 parameters instead normal 3 (no source_object)
    ignore = true
    [[object.property]]
    name = "input-stream"
    #readonly
    ignore = true
    [[object.property]]
    name = "output-stream"
    #readonly
    ignore = true

[[object]]
name = "Gio.InputStream"
status = "generate"
    [[object.function]]
    pattern = "read(_all)?(_async)?"
    #mutable buffer
    ignore = true
    [[object.function]]
    name = "read_bytes_async"
    #wrong async callback type
    ignore = true
    [[object.function]]
    name = "skip_async"
    #wrong async callback type
    ignore = true

[[object]]
name = "Gio.MemoryInputStream"
status = "generate"
    [[object.function]]
    name = "new_from_data"
    #destroy function will called on passed data, so boxing free as in glib::Bytes impossible
    ignore = true
    [[object.function]]
    name = "add_data"
    #destroy function will called on passed data, so boxing free as in glib::Bytes impossible
    ignore = true

[[object]]
name = "Gio.MemoryOutputStream"
status = "generate"
    [[object.function]]
    name = "new"
    #unsupported memory allocators
    ignore = true
    [[object.function]]
    name = "get_data"
    #uncontrolled lifetime
    ignore = true
    [[object.function]]
    name = "get_size"
    #not usable
    ignore = true
    [[object.function]]
    name = "steal_data"
    #unsupported memory allocators
    ignore = true
    [[object.property]]
    name = "data"
    #uncontrolled lifetime
    ignore = true
    [[object.property]]
    name = "size"
    #not usable
    ignore = true
    [[object.property]]
    name = "destroy-function"
    #unsupported memory allocators
    ignore = true
    [[object.property]]
    name = "realloc-function"
    #unsupported memory allocators
    ignore = true

[[object]]
name = "Gio.Notification"
status = "generate"

[[object]]
name = "Gio.OutputStream"
status = "generate"
    [[object.function]]
    name = "splice_async"
    #wrong async callback type
    ignore = true
    [[object.function]]
    name = "write_async"
    #wrong async callback type
    ignore = true
    [[object.function]]
    name = "write_all_async"
    #AsRef<u8>
    ignore = true
    [[object.function]]
    name = "write_bytes_async"
    #wrong async callback type
    ignore = true

[[object]]
name = "Gio.Settings"
status = "generate"
    [[object.signal]]
    name = "writable-change-event"
    inhibit = true

[[object]]
name = "Gio.SimpleAction"
status = "generate"
    [[object.property]]
    name = "parameter-type"
    #value glib::VariantTy
    ignore = true
    [[object.property]]
    name = "state"
    #value glib::VariantTy
    ignore = true

[[object]]
name = "Gio.SimpleIOStream"
status = "generate"
    [[object.property]]
    name = "input-stream"
    #readonly
    ignore = true
    [[object.property]]
    name = "output-stream"
    #readonly
    ignore = true

[[object]]
name = "Gio.Resource"
status = "generate"
    [[object.function]]
    name = "new_from_data"
    # Requires special alignment, see
    # https://bugzilla.gnome.org/show_bug.cgi?id=790030
    ignore = true

[[object]]
name = "Gio.SettingsSchemaKey"
status = "generate"
version = "2.40"
