// This file was generated by gir (5a68ad0) from gir-files (469db10)
// DO NOT EDIT

use ActionGroup;
use DBusConnection;
use RemoteActionGroup;
use ffi;
use glib::translate::*;
use glib_ffi;
use gobject_ffi;
use std::mem;
use std::ptr;

glib_wrapper! {
    pub struct DBusActionGroup(Object<ffi::GDBusActionGroup>): ActionGroup, RemoteActionGroup;

    match fn {
        get_type => || ffi::g_dbus_action_group_get_type(),
    }
}

impl DBusActionGroup {
    pub fn get(connection: &DBusConnection, bus_name: &str, object_path: &str) -> Option<DBusActionGroup> {
        unsafe {
            from_glib_full(ffi::g_dbus_action_group_get(connection.to_glib_none().0, bus_name.to_glib_none().0, object_path.to_glib_none().0))
        }
    }
}
