// This file was generated by gir (5a68ad0) from gir-files (469db10)
// DO NOT EDIT

use ffi;
use glib::translate::*;
use glib_ffi;
use gobject_ffi;
use std::mem;
use std::ptr;

glib_wrapper! {
    pub struct DBusInterfaceInfo(Shared<ffi::GDBusInterfaceInfo>);

    match fn {
        ref => |ptr| ffi::g_dbus_interface_info_ref(ptr),
        unref => |ptr| ffi::g_dbus_interface_info_unref(ptr),
        get_type => || ffi::g_dbus_interface_info_get_type(),
    }
}

impl DBusInterfaceInfo {
    pub fn cache_build(&self) {
        unsafe {
            ffi::g_dbus_interface_info_cache_build(self.to_glib_none().0);
        }
    }

    pub fn cache_release(&self) {
        unsafe {
            ffi::g_dbus_interface_info_cache_release(self.to_glib_none().0);
        }
    }

    //pub fn generate_xml(&self, indent: u32, string_builder: /*Ignored*/glib::String) {
    //    unsafe { TODO: call ffi::g_dbus_interface_info_generate_xml() }
    //}

    //pub fn lookup_method(&self, name: &str) -> /*Ignored*/Option<DBusMethodInfo> {
    //    unsafe { TODO: call ffi::g_dbus_interface_info_lookup_method() }
    //}

    //pub fn lookup_property(&self, name: &str) -> /*Ignored*/Option<DBusPropertyInfo> {
    //    unsafe { TODO: call ffi::g_dbus_interface_info_lookup_property() }
    //}

    //pub fn lookup_signal(&self, name: &str) -> /*Ignored*/Option<DBusSignalInfo> {
    //    unsafe { TODO: call ffi::g_dbus_interface_info_lookup_signal() }
    //}
}
