// This file was generated by gir (5a68ad0) from gir-files (469db10)
// DO NOT EDIT

use AppInfo;
use ffi;
use glib::object::IsA;
use glib::translate::*;
use glib_ffi;
use gobject_ffi;
use std::mem;
use std::ptr;

glib_wrapper! {
    pub struct DesktopAppInfoLookup(Object<ffi::GDesktopAppInfoLookup, ffi::GDesktopAppInfoLookupIface>);

    match fn {
        get_type => || ffi::g_desktop_app_info_lookup_get_type(),
    }
}

pub trait DesktopAppInfoLookupExt {
    fn get_default_for_uri_scheme(&self, uri_scheme: &str) -> Option<AppInfo>;
}

impl<O: IsA<DesktopAppInfoLookup>> DesktopAppInfoLookupExt for O {
    fn get_default_for_uri_scheme(&self, uri_scheme: &str) -> Option<AppInfo> {
        unsafe {
            from_glib_full(ffi::g_desktop_app_info_lookup_get_default_for_uri_scheme(self.to_glib_none().0, uri_scheme.to_glib_none().0))
        }
    }
}
