// This file was generated by gir (5a68ad0) from gir-files (469db10)
// DO NOT EDIT

use Cancellable;
use Error;
use InputStream;
use ffi;
use glib::object::IsA;
use glib::translate::*;
use glib_ffi;
use gobject_ffi;
use std::mem;
use std::ptr;

glib_wrapper! {
    pub struct PollableInputStream(Object<ffi::GPollableInputStream, ffi::GPollableInputStreamInterface>): InputStream;

    match fn {
        get_type => || ffi::g_pollable_input_stream_get_type(),
    }
}

pub trait PollableInputStreamExt {
    fn can_poll(&self) -> bool;

    //fn create_source<'a, P: Into<Option<&'a Cancellable>>>(&self, cancellable: P) -> /*Ignored*/Option<glib::Source>;

    fn is_readable(&self) -> bool;

    fn read_nonblocking<'a, P: Into<Option<&'a Cancellable>>>(&self, buffer: &[u8], cancellable: P) -> Result<isize, Error>;
}

impl<O: IsA<PollableInputStream>> PollableInputStreamExt for O {
    fn can_poll(&self) -> bool {
        unsafe {
            from_glib(ffi::g_pollable_input_stream_can_poll(self.to_glib_none().0))
        }
    }

    //fn create_source<'a, P: Into<Option<&'a Cancellable>>>(&self, cancellable: P) -> /*Ignored*/Option<glib::Source> {
    //    unsafe { TODO: call ffi::g_pollable_input_stream_create_source() }
    //}

    fn is_readable(&self) -> bool {
        unsafe {
            from_glib(ffi::g_pollable_input_stream_is_readable(self.to_glib_none().0))
        }
    }

    fn read_nonblocking<'a, P: Into<Option<&'a Cancellable>>>(&self, buffer: &[u8], cancellable: P) -> Result<isize, Error> {
        let cancellable = cancellable.into();
        let cancellable = cancellable.to_glib_none();
        let count = buffer.len() as usize;
        unsafe {
            let mut error = ptr::null_mut();
            let ret = ffi::g_pollable_input_stream_read_nonblocking(self.to_glib_none().0, buffer.to_glib_none().0, count, cancellable.0, &mut error);
            if error.is_null() { Ok(ret) } else { Err(from_glib_full(error)) }
        }
    }
}
